spring.application.name=demo

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://db.dfgtepnkibqzaysemdmb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Aman99ralhan@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
app.jwtSecret=aE1hS1YyRTVKOFg0TTdQNVE4VDJWNVk5QjJFNUs4WDNNNlA5UThTM1Y2WTk=
app.jwtExpirationMs=86400000
