spring.application.name=demo
server.port=8081

# Supabase PostgreSQL Database Configuration
spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.dfgtepnkibqzaysemdmb
spring.datasource.password=Aman99ralhan@

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
app.jwtSecret=aE1hS1YyRTVKOFg0TTdQNVE4VDJWNVk5QjJFNUs4WDNNNlA5UThTM1Y2WTk=
app.jwtExpirationMs=86400000
